create table bankproduct (
    id varchar(16) primary key,
    name varchar(256) not null default '',
    profit float default 0,
    dayLimit int default 0,
    minMoney float default 0,
    moneyType varchar(32) default '人民币',
    beginDate varchar(32) default '',
    endDate varchar(32) default '',
    area varchar(512) default '',
    company varchar(64) default '',
    profitType varchar(64) default '',
    increaseMoney float default 0,
    profitDate varchar(32) default '',
    riskLevel varchar(32) default '',
    profitInstruction varchar(1024) default '',
    earlyTerminateCondition varchar(1024) default '',
    scope varchar(1024) default '',
    riskWarning varchar(10240) default ''
)